version: '3.7'

services:
  sqldata:
    container_name: db-server
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - product-sqldata:/var/opt/mssql
    networks:
      - vertical-slice 

  redisdata:
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - product-redisdata:/data
    networks:
      - vertical-slice 

  rabbitmq:
    container_name: rabbitmq
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vertical-slice

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - vertical-slice

volumes:
  product-sqldata:
    external: false
  product-redisdata:
    external: false 

networks:
  vertical-slice:
    driver: bridge