
version: "3.7"

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

  redisdata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order/Order.Api/Dockerfile
    depends_on:
      - sqldata
      - redisdata
      - rabbitmq
    extra_hosts:
    - "localhost:192.168.65.2"
