@host=https://localhost:61886

GET {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNjVmMGM5Yy0zYTFkLTQyZjUtYmY0NS0wMzdlNGNmNjMxZTgiLCJnaXZlbl9uYW1lIjoibiIsImZhbWlseV9uYW1lIjoic2RmIiwianRpIjoiODlkMGE1MzAtOTE1Yy00YTRhLTk3OTItNTJmM2FhMzU3N2FjIiwiZXhwIjoxNjc2OTgxODQ3LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.pU_N98MB_WhshqIOvE2CAO_2ftSqglHLsj9SOw1Mg98