@host=https://localhost:61886

POST {{host}}/product/insert
Content-Type: application/json

{
    "firstName": "n",
    "lastName": "sdf",
    "email": "something@email.com",
    "password": "12345"
}


###
GET  {{host}}/product
