version: '3.9'

services:

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Product/Product.Api/Dockerfile
    depends_on:
      - sql
      - redis
      - rabbitmq
    extra_hosts:
    - "localhost:192.168.65.2"